import yaml

from ats.config import CONFIG_DIR
from ats.config import load_hypotheses


def test_every_hypothesis_has_a_why():
    items = load_hypotheses()
    assert items
    for item in items:
        assert item["why"].strip()


def test_hypotheses_file_lists_h1_and_h2():
    raw = yaml.safe_load((CONFIG_DIR / "hypotheses.yaml").read_text(encoding="utf-8"))
    ids = {h["id"] for h in raw["hypotheses"]}
    assert "H1_event_reversal" in ids
    assert "H2_tap_breakout" in ids
    assert "H8_atr_momentum" in ids
    assert "H10_rapid_bullet" in ids
    assert "H9_cot_spec_fade" in ids
    assert "H11_gold_dxy_relink" in ids
    assert "H12_london_close_fade" in ids
    assert "H13_gold_ema200_expand" in ids
    assert "H14_ny_ema_drd" in ids
    assert "H15_ema200_drd_entry" in ids
    assert "H16_ema_13_50_200" in ids
    assert "H17_pdh_pdl_fade" in ids
    assert "H18_large_bar_fade" in ids
    assert "H19_session_vwap_extreme" in ids
    assert "H20_volume_spike_cont" in ids
    assert "H21_round_number_bounce" in ids
    assert "H22_ny_box_fade_vs_break" in ids
    assert "H23_lbma_pm_run" in ids
    assert "H24_month_end_rebalance" in ids
    assert "H25_streak_inventory_fade" in ids
    assert "H26_weekend_gap_fade" in ids
    assert "H27_wm_fix_follow" in ids
    assert "H28_postfix_usd_fade" in ids
    assert "H29_pre_ecb_usd" in ids
    assert "H30_london_asia_break" in ids
    assert "H31_h1_tsmom" in ids
    assert "H32_ranaldo_local_hours" in ids
    assert "H33_inside_bar_break" in ids
    assert "H34_compression_expand" in ids
    assert "H35_friday_flatten" in ids
    assert "H36_overlap_continuation" in ids
    assert "H37_weekend_gap_fx" in ids
    assert "H38_xs_momentum" in ids
    assert "H39_tokyo_lunch_jpy" in ids
    assert "H40_ny_close_asia_fade" in ids
    assert "H41_prior_day_range_fade" in ids
    assert "H42_tokyo_close_flatten" in ids
    assert "H43_month_end_usd" in ids
    assert "H44_wm_postfix_fade" in ids
    assert "H45_big_figure_fade" in ids
    assert "H46_stop_pool_20_fade" in ids
    assert "H47_london_lunch_fade" in ids
    assert "H48_london_ist_break" in ids
    assert "H49_london_ist_break_gold" in ids
    assert "H50_london_fib_bounce" in ids
    assert "H51_ny_sweep_follow" in ids
    assert "H52_carry_roll" in ids
    assert "H53_tokyo_fix_follow" in ids
    assert "H54_comex_open_follow" in ids
    assert "H55_nyse_open_eur" in ids
    assert "H56_comex_close_fade" in ids
    assert "H57_sge_open_follow" in ids
    assert "H76_hkex_open_aud" in ids
    assert "H77_imm_usd_bid" in ids
    assert "H78_two_day_fade" in ids
    assert "H79_overnight_usd" in ids
    assert "H80_nfp_cpi_fade" in ids
    assert "H81_fomc_fade" in ids
    assert "H82_month_start_usd" in ids
    assert "H83_eur_cot_fade" in ids
    assert "H84_jpy_cot_fade" in ids
    assert "H85_gbp_cot_fade" in ids
    assert "H86_weekend_gap_g10" in ids
    assert "H87_monday_cash_gbp" in ids
    assert "H88_monday_cash_jpy" in ids
    assert "H89_monday_cash_aud" in ids
    assert "H90_ny_cut_eur" in ids
    assert "H91_ny_cut_gbp" in ids
    assert "H92_ny_cut_jpy" in ids
    assert "H93_wm_postfix_eur" in ids
    assert "H94_wm_postfix_gbp" in ids
    assert "H95_wm_postfix_jpy" in ids
    assert "H96_asia_box_gold" in ids
    assert "H97_asia_box_gbp" in ids
    assert "H98_asia_box_aud" in ids
    assert "H99_tokyo_roll_jpy" in ids
    assert "H100_tokyo_roll_eur" in ids
    assert "H101_tokyo_roll_gbp" in ids
    assert "H102_overnight_xs_fade" in ids
    assert "H103_cls_settle_eur" in ids
    assert "H104_cls_settle_gbp" in ids
    assert "H105_cls_settle_jpy" in ids
    assert "H106_silver_bullet_eur" in ids
    assert "H107_silver_bullet_gbp" in ids
    assert "H108_silver_bullet_gold" in ids
    assert "H109_asx_close_fade" in ids
    assert "H110_nzx_close_fade" in ids
    assert "H111_tsx_close_fade" in ids
    assert "H112_london_open_eur" in ids
    assert "H113_london_open_gbp" in ids
    assert "H114_london_open_gold" in ids
    assert "H115_eia_cad" in ids
    assert "H116_eia_aud" in ids
    assert "H117_eia_gold" in ids
    assert "H118_london_orb_eur" in ids
    assert "H119_london_orb_gbp" in ids
    assert "H120_london_orb_gold" in ids
    assert "H121_tokyo_orb_jpy" in ids
    assert "H122_tokyo_orb_eur" in ids
    assert "H123_tokyo_orb_gold" in ids
    assert "H124_prior_hour_eur" in ids
    assert "H125_prior_hour_gbp" in ids
    assert "H126_prior_hour_gold" in ids
    assert "H127_hour_close_eur" in ids
    assert "H128_hour_close_gbp" in ids
    assert "H129_hour_close_gold" in ids
    assert "H130_hour_gap_eur" in ids
    assert "H131_hour_gap_gbp" in ids
    assert "H132_hour_gap_gold" in ids
    assert "H133_us830_slot_eur" in ids
    assert "H134_us830_slot_gbp" in ids
    assert "H135_us830_slot_gold" in ids
    assert "H136_pdc_tag_eur" in ids
    assert "H137_pdc_tag_gbp" in ids
    assert "H138_pdc_tag_gold" in ids
    assert "H139_tnext_roll_eur" in ids
    assert "H140_tnext_roll_gbp" in ids
    assert "H141_tnext_roll_gold" in ids
    assert "H142_syd09_fade_aud" in ids
    assert "H143_syd09_fade_nzd" in ids
    assert "H144_syd09_fade_gold" in ids
    assert "H145_ldn10_cut_eur" in ids
    assert "H146_ldn10_cut_gbp" in ids
    assert "H147_ldn10_cut_jpy" in ids
    assert "H148_ldn05_hand_eur" in ids
    assert "H149_ldn05_hand_gbp" in ids
    assert "H150_ldn05_hand_gold" in ids
    assert "H151_tgt18_fade_eur" in ids
    assert "H152_tgt18_fade_chf" in ids
    assert "H153_tgt18_fade_gold" in ids
    assert "H154_tyo13_reopen_jpy" in ids
    assert "H155_tyo13_reopen_eur" in ids
    assert "H156_tyo13_reopen_gold" in ids
    assert "H157_oil1430_fade_cad" in ids
    assert "H158_oil1430_fade_aud" in ids
    assert "H159_oil1430_fade_gold" in ids
    assert "H160_ldnbox_ny_eur" in ids
    assert "H161_ldnbox_ny_gbp" in ids
    assert "H162_ldnbox_ny_gold" in ids
    assert "H163_akl09_fade_nzd" in ids
    assert "H164_akl09_fade_aud" in ids
    assert "H165_akl09_fade_gold" in ids
    assert "H166_zur12_fade_chf" in ids
    assert "H167_zur12_fade_eur" in ids
    assert "H168_zur12_fade_gold" in ids
    assert "H169_tyo11_fade_jpy" in ids
    assert "H170_tyo11_fade_eur" in ids
    assert "H171_tyo11_fade_gold" in ids
    assert "H172_lbma_am_gold" in ids
    assert "H173_lbma_am_aud" in ids
    assert "H174_lbma_am_nzd" in ids
    assert "H175_sge15_fade_gold" in ids
    assert "H176_sge15_fade_aud" in ids
    assert "H177_sge15_fade_jpy" in ids
    assert "H178_mcx09_fade_gold" in ids
    assert "H179_mcx09_fade_aud" in ids
    assert "H180_mcx09_fade_jpy" in ids
    assert "H181_nybox_pm_eur" in ids
    assert "H182_nybox_pm_gbp" in ids
    assert "H183_nybox_pm_gold" in ids
    assert "H184_dxb14_fade_gold" in ids
    assert "H185_dxb14_fade_aud" in ids
    assert "H186_dxb14_fade_jpy" in ids
    assert "H187_sgx17_fade_aud" in ids
    assert "H188_sgx17_fade_jpy" in ids
    assert "H189_sgx17_fade_gold" in ids
    assert "H190_xetra1730_fade_eur" in ids
    assert "H191_xetra1730_fade_gbp" in ids
    assert "H192_xetra1730_fade_gold" in ids
    assert "H193_ovn_intraday_fade_eur" in ids
    assert "H194_ovn_intraday_fade_gold" in ids
    assert "H195_gold_h1_tsmom" in ids
    assert "H196_fedwire18_fade_eur" in ids
    assert "H207_hk12_fade_gold" in ids
